export const COMPLAINTS = [
  {
    _id: "1",
    title: "WiFi Connectivity Issue",
    description: "The WiFi in our building is constantly down! Please fix it ASAP! ⚠️",
    severity: "Major",
    category: "#TechnicalProblem",
    img: "../../../cover.png",
    user: {
      rollNo: "2301420100153",
      profileImg: "/avatars/boy1.png",
    },
    likes: ["6658s891", "6658s892", "6658s893"],
  },
  {
    _id: "2",
    title: "Projector Not Working",
    description: "The classroom projector isn't working! 😩 Can someone fix it before the lecture?",
    severity: "Moderate",
    category: "#FacilitiesIssue",
    img: "../../../cover.png",
    user: {
      rollNo: "2301420100154",
      profileImg: "/avatars/girl1.png",
    },
    likes: ["6658s893", "6658s894", "6658s895", "6658s896"],
  },
  {
    _id: "3",
    title: "Assignment Submission Issue",
    description: "I need help with my assignment submission. It’s not working, please check. 🤔",
    severity: "Minor",
    category: "#GeneralIssue",
    user: {
      rollNo: "2301420100155",
      profileImg: "/avatars/boy2.png",
    },
    likes: ["6658s897", "6658s898"],
  },
  {
    _id: "4",
    title: "AC Not Cooling",
    description: "The AC in the computer lab is not cooling properly. It's way too hot in here. 🔥",
    severity: "Major",
    category: "#FacilitiesIssue",
    img: "../../../cover.png",
    user: {
      rollNo: "2301420100156",
      profileImg: "/avatars/girl2.png",
    },
    likes: ["6658s899", "6658s900", "6658s901", "6658s902"],
  },
  {
    _id: "5",
    title: "Broken Chair in Library",
    description: "There’s a broken chair in the library. Someone might get hurt! Please fix it ASAP! ⚠️",
    severity: "Moderate",
    category: "#FacilitiesIssue",
    img: "../../../cover.png",
    user: {
      rollNo: "2301420100157",
      profileImg: "/avatars/boy3.png",
    },
    likes: ["6658s903", "6658s904", "6658s905"],
  },
];
